### ISSUE TITLE
Big cube notation isn't working properly

### ISSUE THREAD

**Issue by cubizh** [Cride5/visualcube#1]
?fmt=png&size=200&pzl=6&alg=3Rw

works as it should, however, something like

?fmt=png&size=200&pzl=6&alg=y3Rw

only does a two layer Rw.

Seems it's understanding "y3" instead of "3Rw". Since y3 == y', perhaps this behaviour could be changed for this case, since there's no other way do it?

**Comment by Cride5** [comment]
Hi, If you insert a space in the algorithm it will resolve this
ambiguous case: alg=y 3Rw

If you want to avoid the %20 character that space expands to, it can
also be expressed like this: alg=y+3Rw

Conrad

On 31/08/15 03:49, cubizh wrote:

> ?fmt=png&size=200&pzl=6&alg=3Rw
> 
> works as it should, however, something like
> 
> ?fmt=png&size=200&pzl=6&alg=y3Rw
> 
> only does a two layer Rw.
> 
> Seems it's understanding "y3" instead of "3Rw". Since y3 == y', perhaps
> this behaviour could be changed for this case, since there's no other
> way do it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cride5/visualcube/issues/1.

## 

Conrad Rider
cride5@crider.co.uk
www.crider.co.uk

**Comment by cubizh** [comment]
I was unaware of that aditional syntax, perfect. Thanks :)
