### ISSUE TITLE
Only the "svg" format appears to be supported

### ISSUE THREAD

**Issue by cbeust** [Cride5/visualcube#7]
I tried `png`, `gif`, `jpg` but all I get is a blank page. For example, here is the cube from the main page with just the `fmt` parameter altered to `png`:

[Buggy cube](http://cube.crider.co.uk/visualcube.php?fmt=png&size=200&alg=S2M2E2).

**Comment by lukemaurer** [comment]
This seems as likely to be a server misconfiguraton as a bug in the code here. (The mapping from .png to .php?fmt=png also seems to be broken, and that's definitely a config issue.)

**Comment by Cride5** [comment]
This feature requires configuration of mod_rewrite on the server to redirect image suffixes to fmt=xxx form. I've added instructions into the README.md to describe how to do this. Thanks for the report.
